name: actions.yml
on: [push]
jobs:
  Golang-check:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut Code
        uses: actions/checkout@v5

      - name: Setup Golang
        uses: actions/setup-go@v7
        with:
          go-version: '1.26'
          cache: true
      - name: Download Dependencies
        run: go mod download
      - name: Testing Go
        run: go test ./...
      - name: Build
        run: go build -v ./...
      



